### ISSUE TITLE
GnuTLS dlls are not included in the artifact when using dotnet publish

### ISSUE THREAD

**Issue by FanDjango** [robinrodricks/FluentFTP.GnuTLS#77]
See https://github.com/robinrodricks/FluentFTP/issues/1274

**Comment by FanDjango** [comment]
@rob-hendrickx-c4t @fredericDelaporte

Remember this post: (over in FluentFTP)

@FanDjango I ended up fixing it for my case locally with following targets file

<Project>
  <ItemGroup>
    <Files Include="$(MSBuildThisFileDirectory)/../content/*.dll" />
  </ItemGroup>
  <Target Name="CopyFiles" AfterTargets="Build">
    <Copy SourceFiles="@(Files)" DestinationFolder="$(TargetDir)" />
  </Target>
  <Target Name="CopyFilesPublish" AfterTargets="Publish" Condition="$(AzureFunctionsVersion) == ''">
    <Copy SourceFiles="@(Files)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="CopyFilesPublishFunctions" AfterTargets="Publish" Condition="$(AzureFunctionsVersion) != ''">
    <Copy SourceFiles="@(Files)" DestinationFolder="$(PublishDir)/bin" SkipUnchangedFiles="true" />
  </Target>
</Project>
First Copy will act on build of the consumer
Second copy will act on publish of the consumer if it is not an Azure Function.
Third copy will act on publish of the consumer if it is an Azure Function

I'll leave it for you to consider whether or not it could be used as inspiration for extending the targets file of FluentFTP.GnuTLS. My problem is fixed at least :) Thanks!

I am sort of reluctant to touch what is a "working running system" (at least for most others).

Cannot one of you try your hand at a PR for the base .csproj as a starting point. I have no experience whatsoever with dotnet publish and further deployment so you guys would be the best choice to get this working. I am willing to make/merge the changes, release Nuget and then you can test, maybe some iterations and we can fix this?

Otherwise let's leave it open is some fashion so others can solve it locally.

**Comment by fredericDelaporte** [comment]
On my side, I have used a workaround. I have put an additional copy task in my Azure pipeline, in order to grab the binaries from the build folder and put them in the publish folder. Quick&dirty. Having it work directly without this hack would be a nice to have. Not having it is not a blocker for me.

So, in my build pipeline, I have something like this:
```yaml
    - task: CopyFiles@2
      displayName: 'Copy GnuTLS binaries' # Todo: if https://github.com/robinrodricks/FluentFTP.GnuTLS/issues/77 is fixed and FluentFTP.GnuTLS updated to the fixed version, remove this task.
      inputs:
        SourceFolder: '$(build.sourcesDirectory)\TheProjectDir\bin'
        Contents: '**\lib*.dll'
        TargetFolder: TheTargetDir
        flattenFolders: true
```
